<?php

declare (strict_types=1);
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */
namespace Magento\Backend\Setup;

use Magento\Framework\App\Deployment_Config;
use Magento\Framework\Config\Data\Config_Data;
use Magento\Framework\Config\File\Config_File_Pool;
use Magento\Framework\Setup\Backend_Frontname_Generator;
use Magento\Framework\Setup\Config_Options_List_Interface;
use Magento\Framework\Setup\Option\Text_Config_Option;
/**
 * Deployment configuration options needed for Backend module
 *
 */
class Config_Options_List implements Config_Options_List_Interface
{
    /**
     * Input key for the options
     */
    public const INPUT_KEY_BACKEND_FRONTNAME = 'backend-frontname';
    /**
     * Path to the values in the deployment config
     */
    public const CONFIG_PATH_BACKEND_FRONTNAME = 'backend/frontName';
    /**
     * {@inheritdoc}
     */
    public function get_options()
    {
        return [new Text_Config_Option(self::INPUT_KEY_BACKEND_FRONTNAME, Text_Config_Option::FRONTEND_WIZARD_TEXT, self::CONFIG_PATH_BACKEND_FRONTNAME, 'Backend frontname (will be autogenerated if missing)')];
    }
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function create_config(array $options, Deployment_Config $deployment_config)
    {
        $config_data = new Config_Data(Config_File_Pool::APP_ENV);
        if (!$deployment_config->get(self::CONFIG_PATH_BACKEND_FRONTNAME) && !isset($options[self::INPUT_KEY_BACKEND_FRONTNAME])) {
            $options[self::INPUT_KEY_BACKEND_FRONTNAME] = Backend_Frontname_Generator::generate();
        }
        if (isset($options[self::INPUT_KEY_BACKEND_FRONTNAME])) {
            $config_data->set(self::CONFIG_PATH_BACKEND_FRONTNAME, $options[self::INPUT_KEY_BACKEND_FRONTNAME]);
        }
        return [$config_data];
    }
    /**
     * {@inheritdoc}
     */
    public function validate(array $options, Deployment_Config $deployment_config)
    {
        $errors = [];
        if (isset($options[self::INPUT_KEY_BACKEND_FRONTNAME]) && !preg_match('/^[a-zA-Z0-9_]+$/', $options[self::INPUT_KEY_BACKEND_FRONTNAME])) {
            $errors[] = "Invalid backend frontname '{$options[self::INPUT_KEY_BACKEND_FRONTNAME]}'";
        }
        return $errors;
    }
}