<?php

/**
 * Copyright 2022 Adobe
 * All Rights Reserved.
 */
declare (strict_types=1);
namespace Magento\Bundle\Plugin\Framework\Data\Form\Element;

use Magento\Framework\Data\Form\Element\Abstract_Element;
use Magento\Framework\Data\Form\Element\Fieldset;
/**
 * Plugin that fixes mapping of value and label for bundle dynamic attributes
 */
class Fieldset_Plugin
{
    /**
     * @var string[]
     */
    private $dynamic_attribute_names = ['sku_type', 'weight_type', 'price_type'];
    /**
     * Normalise bundle dynamic attributes values
     *
     * Normalise attribute values for bundle dynamic attributes generated by form element
     * to make it consistent across the system (dynamic => 1, fixed => 0)
     *
     * @param Fieldset $subject
     * @param AbstractElement $result
     * @return AbstractElement
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function after_add_field(Fieldset $subject, Abstract_Element $result)
    {
        if (!in_array($result->get_attribute_code(), $this->dynamic_attribute_names)) {
            return $result;
        }
        $new = [];
        foreach ($result->get_values() as $option) {
            $option['value'] = (int) !$option['value'];
            $new[] = $option;
        }
        $result->set_values($new);
        return $result;
    }
}