<?php

declare (strict_types=1);
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */
namespace Magento\Captcha\Model;

/**
 * Captcha Model Interface
 *
 * @api
 * @since 100.0.2
 */
interface Captcha_Interface
{
    /**
     * Generates captcha
     *
     * @abstract
     * @return void
     */
    public function generate();
    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @param string $word
     * @return bool
     * @abstract
     */
    public function is_correct($word);
    /**
     * Get Block Name
     * @return string
     */
    public function get_block_name();
}